config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'static_pages#top'
  get  '/explanation',    to: 'static_pages#explanation'

  resources :maps, only: [:index, :create] do
    resources :boards, only: [:index, :create, :destroy]
  end

  resources :users, only: [:index, :edit, :update, :destroy]do
    resources :log_books, only: [:index,:create, :edit, :update, :show, :new, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_one_attached :image
  belongs_to :map_place
  belongs_to :user

  validates :content, presence: true, unless: :was_attached?
  validate :image_content_type, if: :was_attached?
  def image_content_type
    errors.add(:image, 'にはjpegまたはpngファイルを添付してください') unless image.content_type.in?(%('image/jpeg image/png'))
  end

  def was_attached?
    image.attached?
  end
end

app/models/log_book.rb
class LogBook < ApplicationRecord
  validates :place, presence: true

  belongs_to :user
end

app/models/map_place.rb
class MapPlace < ApplicationRecord
  with_options presence: true do
    validates :place_name
    validates :latitude
    validates :longitude
  end

  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
  validate :avatar_content_type, if: :was_attached?

  has_one_attached :avatar
  has_many :log_books
  has_many :comments

  def avatar_content_type
    errors.add(:avatar, 'にはjpegまたはpngファイルを添付してください') unless avatar.content_type.in?(%('image/jpeg image/png'))
  end

  def was_attached?
    avatar.attached?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(_resource)
    maps_path
  end

  def after_sign_in_path_for(_resource)
    maps_path
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :nickname, :birth_date, :self_introduction, :avatar])
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  before_action :set_map_place, only: [:index, :create]

  def index
    @comment = Comment.new
    @comments = @map_place.comments.all
  end

  def create
    @comment = @map_place.comments.new(comment_params)
    if @comment.save
      redirect_to map_boards_path(@map_place)
    else
      @comments = @map_place.comments.all
      render :index
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if current_user.id == @comment.user_id
      @comment.destroy
      redirect_to map_boards_path
    else
      render :index
    end
  end

  private

  def set_map_place
    @map_place = MapPlace.find(params[:map_id])
  end

  def comment_params
    params.require(:comment).permit(:content, :image).merge(user_id: current_user.id, map_place_id: params[:map_id])
  end
end

app/controllers/log_books_controller.rb
class LogBooksController < ApplicationController
  before_action :move_to_map, except: [:show]
  before_action :authenticate_user!
  before_action :set_log_book, only: [:show, :edit, :update, :destroy]

  def index
    @log_books = LogBook.all
  end

  def new
    @log_book = LogBook.new
  end

  def create
    @log_book = LogBook.new(log_book_params)
    if @log_book.save
      redirect_to user_log_book_path(current_user.id, @log_book.id)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @log_book.update(log_book_params)
      redirect_to user_log_book_path(params[:id])
    else
      render :new
    end
  end

  def destroy
    if current_user.id == @log_book.user_id
      @log_book.destroy
      redirect_to users_path
    else
      redirect_to users_path
    end
  end

  private

  def log_book_params
    params.require(:log_book).permit(:place, :temperature, :water_temperature, :transparency, :en_time, :ex_time, :deep_avg,
                                     :deep_max, :weight, :wear, :free_space, :member).merge(user_id: current_user.id)
  end

  def move_to_map
    redirect_to maps_path unless user_signed_in?
  end

  def set_log_book
    @log_book = LogBook.find(params[:id])
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
    @map_place = MapPlace.new
    @map_places = MapPlace.paginate(page: params[:page], per_page: 30)
    gon.map_places = MapPlace.all
  end

  def create
    @map_place = MapPlace.new(map_place_params)
    if @map_place.save
      redirect_to maps_path
    else
      redirect_to maps_path
    end
  end

  private

  def map_place_params
    params.require(:map_place).permit(:place_name, :description, :latitude, :longitude)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def explanation
  end

  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    # @log_books = LogBook.paginate(page: params[:page], per_page: 30).includes(:user)
    @log_books = LogBook.includes(:user)
    @user = User.find(current_user.id)
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(params[:id])
    if @user.update(set_params)
      redirect_to users_path(current_user.id)
    else
      render :index
    end
  end

  private

  def set_params
    params.require(:user).permit(:avatar, :nickname, :email, :self_introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/log_books_helper.rb
module LogBooksHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/index.html.erb
<h1 class="container"><%= @map_place.place_name %></h1>
</div>
<div class="messages">
  <%= render partial: 'shared/comment', collection: @comments %>
</div>
<footer>
<%= form_with model: [@map_place, @comment],url: map_boards_path,method: :POST, class: 'form', local: true do |f| %>
  <div class="form-input">
    <%= f.text_field :content, class: 'form-message', placeholder: '日付け、魚種、透明度etc' %>
    <label class="form-image">
      <span class="image-file">画像</span>
      <%= f.file_field :image, class: 'hidden' %>
    </label>
  </div>
  <%= f.submit '送信', class: 'form-submit' %>
  <div id="image-list"></div>
<% end %>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LeGrandBleu2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= include_gon %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  <![endif]-->

  <body>
  <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/log_books/edit.html.erb
ログブック編集
<div class="box26  bg-white">
<span class="box-title2">log bock</span>
<%= form_with(model: @log_book, url: user_log_book_path,method: :PUT ,local: true) do |form| %>
<div class="place_name">
  <div class="field">
    <%= form.text_field :place, placeholder: "必須", id: "place_name", class: 'spot_text' %>
    <%= form.label :place, "場所名", class: 'spot_name' %>
    <span class="focus_line"></span>
  </div>
</div>
<div class="top-line">
  <div class="weight">
    <div class="field">
      <%= form.text_field :weight, placeholder: "", id: "place_name", class: 'spot_text' %><p class="unit">kg</p>
      <%= form.label :weight, "重り", class: 'spot__title' %>
      <span class="focus_line"></span>
    </div>
  </div>
  <div class="transparency">
    <div class="field">
      <%= form.text_field :transparency ,class: 'spot_text', placeholder: ""%><p class="unit">m</p>
      <%= form.label :transparency, "透明度" %>
      <span class="focus_line"></span>
    </div>
  </div>
</div>
  <div class="en-ex-time">
    <div class="field">
      <%= form.text_field :en_time, placeholder: "", id: "place_name", class: 'spot_text' %>
      <%= form.label :en_time, "始めた時間", class: 'spot__title' %>
      <span class="focus_line"></span>
    </div>
    <div class="field">
      <%= form.text_field :ex_time, placeholder: "",class: 'spot_text' %>
      <%= form.label :ex_time, "出た時間" %>
      <span class="focus_line"></span>
    </div>
  </div>
  <div class="temp">
    <div class="field">
      <%= form.text_field :temperature, placeholder: "気温",class: 'spot_text', placeholder: "" %>
      <%= form.label :temperature, "気温",class: 'temperature' %>
      <span class="focus_line"></span>
    </div>
    <div class="field">
      <%= form.text_field :water_temperature,class: 'spot_text', placeholder: "" %>
      <%= form.label :water_temperature, "水温" %>
      <span class="focus_line"></span>
    </div>
  </div>
  <div class="deep-avg-max">
    <div class="field">
      <%= form.text_field :deep_avg,class: 'spot_text', placeholder: "" %>
      <%= form.label :deep_avg, "平均潜水時間" %>
      <span class="focus_line"></span>
    </div>
    <div class="field">
      <%= form.text_field :deep_max,class: 'spot_text', placeholder: "" %>
      <%= form.label :deep_max, "最大深度" %>
      <span class="focus_line"></span>
    </div>
  </div>
<div class="third-line">
  <div class="wear">
    <div class="field">
      <%= form.text_field :wear, class: 'spot_text' %>
      <%= form.label :wear, "服装" %>
      <span class="focus_line"></span>
    </div>
  </div>
  <div class="member">
    <div class="field">
      <%= form.text_field :member,class: 'spot_text' %>
      <%= form.label :member, "メンバー" %>
      <span class="focus_line"></span>
    </div>
  </div>
</div>
<div class="free">
  <div class="field2">
    <%= form.text_area :free_space, class: 'spot_text2',placeholder: "自由にかく" %>
    <%= form.label :free_space, "自由にかく" %>
    
  </div>
</div>
<div class="actions">
  <%= form.submit "作成", type: 'button', onclick: 'submit();' %>
</div>
<% end %>
</div>

app/views/log_books/index.html.erb
ログブック一覧

app/views/log_books/new.html.erb
ログブック作成
<body class="box100">
<div class="box333"> 
<div class="box26  ">
<span class="box-title2">log book作成</span>
<%= form_with(model: @log_book, url: user_log_books_path,method: :POST ,local: true) do |form| %>
<%# <%= render 'shared/error_messages', model: form.object %>
<div class="place_name">
  <div class="field">
    <%= form.text_field :place, id: "place_name", class: 'spot_text', placeholder: "必須"%>
    <%= form.label :place, "場所名", class: 'spot_name' %>
    <span class="focus_line"></span>
  </div>
</div>
<div class="top-line">
  <div class="weight">
    <div class="field">
      <%= form.text_field :weight, placeholder: "", id: "place_name", class: 'spot_text' %><p class="unit">kg</p>
      <%= form.label :weight, "重り", class: 'spot__title' %>
      <span class="focus_line"></span>
    </div>
  </div>
  <div class="transparency">
    <div class="field">
      <%= form.text_field :transparency ,class: 'spot_text', placeholder: ""%><p class="unit">m</p>
      <%= form.label :transparency, "透明度" %>
      <span class="focus_line"></span>
    </div>
  </div>
</div>
  <div class="en-ex-time">
    <div class="field">
      <%= form.text_field :en_time, placeholder: "", id: "place_name", class: 'spot_text' %>
      <%= form.label :en_time, "始めた時間", class: 'spot__title' %>
      <span class="focus_line"></span>
    </div>
    <div class="field">
      <%= form.text_field :ex_time, placeholder: "",class: 'spot_text' %>
      <%= form.label :ex_time, "出た時間" %>
      <span class="focus_line"></span>
    </div>
  </div>
  <div class="temp">
    <div class="field">
      <%= form.text_field :temperature, placeholder: "",class: 'spot_text' %>
      <%= form.label :temperature, "気温",class: 'temperature' %>
      <span class="focus_line"></span>
    </div>
    <div class="field">
      <%= form.text_field :water_temperature,class: 'spot_text', placeholder: "" %>
      <%= form.label :water_temperature, "水温" %>
      <span class="focus_line"></span>
    </div>
  </div>
  <div class="deep-avg-max">
    <div class="field">
      <%= form.text_field :deep_avg,class: 'spot_text', placeholder: "" %>
      <%= form.label :deep_avg, "平均潜水時間" %>
      <span class="focus_line"></span>
    </div>
    <div class="field">
      <%= form.text_field :deep_max,class: 'spot_text', placeholder: "" %>
      <%= form.label :deep_max, "最大深度" %>
      <span class="focus_line"></span>
    </div>
  </div>
<div class="third-line">
  <div class="wear">
    <div class="field">
      <%= form.text_field :wear, placeholder: "", class: 'spot_text' %>
      <%= form.label :wear, "服装" %>
      <span class="focus_line"></span>
    </div>
  </div>
  <div class="member">
    <div class="field">
      <%= form.text_field :member,class: 'spot_text' %>
      <%= form.label :member, "メンバー" %>
      <span class="focus_line"></span>
    </div>
  </div>
</div>
<div class="free">
  <div class="field2">
    <%= form.text_area :free_space, class: 'spot_text2',placeholder: "free space" %>
    <%= form.label :free_space, "自由にかく" %>
    
  </div>
</div>
<div class="actions">
  <%= form.submit "作成" %>
</div>
<% end %>
</div>
</body>

app/views/log_books/show.html.erb
ログブック詳細
<body class="box100">
<div class="container">
  <div class="box333"> 
    <div class="box26  ">
        <span class="box-title2"><%= @log_book.place %></span>
        <h3>場所</h3><%= @log_book.weight %>
        <h6>透明度</h6><%= @log_book.transparency %>
        <h6>始めた時間</h6><%= @log_book.en_time %>
        <h6>出た時間</h6><%= @log_book.ex_time %>
        <h6>気温</h6><%= @log_book.temperature %>
        <h6>水温</h6><%= @log_book.water_temperature %>
        <h6>平均潜水深度</h6><%= @log_book.deep_avg %>
        <h6>最大潜水深度</h6><%= @log_book.deep_max %>
        <h6>装備</h6><%= @log_book.wear %>
        <h6>メンバー</h6><%= @log_book.member %>
        <h6>freespace</h6><%= @log_book.free_space %>
    </div>
  </div>
</div>
</body>

app/views/maps/_googlemap.html.erb
<div id="map" class="container">
 <script>
    var marker = [];
    var infoWindow = [];
    function initMap() {
        var latlng = new google.maps.LatLng( 34.808502, 135.639683 );//中心の緯度, 経度
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 8,//ズームの調整
          center: latlng, //上で設定した中心
          // コントロールの表示
          fullscreenControl: false,
          mapTypeControl: false,
          styles:
          [
    { "featureType": "administrative", "elementType": "labels.text.fill", "stylers": [
            { "color": "#e85113"}
        ]
    },
    { "featureType": "administrative", "elementType": "labels.text.stroke", "stylers": [
            { "color": "#ffffff"},
            { "weight": 6 }
        ]
    },
    { "featureType": "landscape", "elementType": "all", "stylers": [
            { "lightness": 20 },
            { "color": "#efe9e4" }
        ]
    },
    { "featureType": "landscape","elementType": "labels", "stylers": [
            { "visibility": "off" }
        ]
    },
    { "featureType": "landscape.man_made", "elementType": "all", "stylers": [
            { "visibility": "off" }
        ]
    },
    { "featureType": "poi", "elementType": "geometry", "stylers": [
            { "visibility": "on" },
            { "color": "#f0e4d3" }
        ]
    },
    { "featureType": "poi", "elementType": "labels", "stylers": [
            { "visibility": "simplified"}
        ]
    },
    {"featureType": "poi",  "elementType": "labels.text.fill", "stylers": [
            { "hue": "#11ff00"}
        ]
    },
    { "featureType": "poi", "elementType": "labels.text.stroke", "stylers": [
            { "lightness": 100 }
        ]
    },
    { "featureType": "poi", "elementType": "labels.icon", "stylers": [
            { "hue": "#4cff00" },
            { "saturation": 58 }
        ]
    },
    { "featureType": "road", "elementType": "labels.text.fill", "stylers": [
            { "lightness": -100 }
        ]
    },
    { "featureType": "road", "elementType": "labels.text.stroke", "stylers": [
            {"lightness": 100 }
        ]
    },
    { "featureType": "road.highway",  "elementType": "geometry.fill", "stylers": [
            { "color": "#efe9e4" },
            { "lightness": -25 }
        ]},
    { "featureType": "road.highway", "elementType": "geometry.stroke", "stylers": [
            {  "color": "#efe9e4" },
            { "lightness": -40 }
        ]},
    { "featureType": "road.arterial",  "elementType": "geometry.fill", "stylers": [
            { "color": "#efe9e4"},
            {"lightness": -10 }
        ]},
    { "featureType": "road.arterial", "elementType": "geometry.stroke", "stylers": [
            { "color": "#efe9e4"},
            { "lightness": -20 }
        ]},
    { "featureType": "water",  "elementType": "all", "stylers": [
            { "color": "#19a0d8" }
        ]},
    { "featureType": "water", "elementType": "labels.text.fill", "stylers": [
            { "lightness": -100 }
        ]},
    { "featureType": "water", "elementType": "labels.text.stroke", "stylers": [
            { "lightness": 100 }
        ]}]
        });
        
        for (var i = 0; i < gon.map_places.length; i++) {
          markerLatLng = new google.maps.LatLng({lat: gon.map_places[i].latitude, lng: gon.map_places[i].longitude}); // 緯度経度のデータ作成
          marker[i] = new google.maps.Marker({ position: markerLatLng,
           map: map,
        //    icon: new google.maps.MarkerImage(
        //         '../assets/images/dolfin_icon.png',
        //         new google.maps.Size(60, 80)//マーカー画像のサイズ
        //    )
            });

         infoWindow[i] = new google.maps.InfoWindow({ // 吹き出しの追加
         content: ` <div class="sample"><a href="/maps/${gon.map_places[i].id}/boards">${gon.map_places[i].place_name}</div>` // 吹き出しに表示する内容
       });
 
        markerEvent(i); // マーカーにクリックイベントを追加
 
  }
}
 
// マーカーにクリックイベントを追加
function markerEvent(i) {
    marker[i].addListener('click', function() { // マーカーをクリックしたとき
      infoWindow[i].open(map, marker[i]); // 吹き出しの表示
  });
        };
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["GOOGLEMAP_KEY"] %>&callback=initMap"></script>
<script> src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"</script>
</div>

app/views/maps/index.html.erb
<div class="container">
  <%= render "googlemap"%>
</div>
<div class="container mt-4 bg-white text-dark box1" style="padding:10px;">
<span class="box-title">掲示板一覧</span>
  <%= will_paginate @map_places %>
    <ul class="map_places">
      <% @map_places.each do |map_place| %>
        <li class='list'>
          <%= link_to map_place.place_name, "/maps/#{map_place.id}/boards" %>
        </li>
      <% end %>
    </ul>
  <%= will_paginate @map_places %>
</div>
<% if !current_user.nil? && current_user.admin? %>
<%= form_with(model: @map_place, url: maps_path, local: true) do |form| %>
      <h3 class="map-title">掲示板を作成</h3>
      <div class="field3">
        <%= form.label :place_name, "場所名", class: 'spot__title' %>
        <%= form.text_field :place_name, placeholder: "スポットを入力", id: "place_name", class: 'spot__text' %>
      </div>
      <div class="field3">
        <%= form.label :latitude, "緯度" %>
        <%= form.text_field :latitude %>
      </div>
      <div class="field3">
        <%= form.label :longitude, "経度" %>
        <%= form.text_field :longitude %>
      </div>
      <div class="actions">
        <%= form.submit "作成" %>
      </div>
    <% end %>
<% end %>

app/views/shared/_comment.html.erb
<div class="message">
  <div class="upper-message">
    <div class="message-user">
      <!-- 投稿したユーザー名情報を出力する -->
      <%= comment.user.nickname %>
    </div>
    <div class="message-date">
      <!-- 投稿した時刻を出力する -->
      <%= l comment.created_at %>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-content">
      <!-- 投稿したメッセージ内容を記述する -->
      <%= comment.content %>
    </div>
    <%= image_tag comment.image.variant(resize: '300x300'), class: 'message-image' if comment.image.attached? %>
    <% if user_signed_in? && (current_user.id == comment.user_id) %>
      <%= link_to '削除',  map_board_path(params[:map_id],comment.id), method: :delete, class: "log-book-path" ,id: "aaa"%>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header>        
  <nav class="navbar navbar-default navbar-expand-lg py-0 navbar-light color__navi">
    <div class="container-fluid font-weight-bold ">
      <a class="navbar-brand " href="#">
        <h2 class="mb-0 font-weight-bold le_grand_bleu">
            LeGrandBleu
        </h2>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent"
        aria-controls="navbarContent" aria-expanded="false" aria-label="スマートフォン用ナビゲーション">
        <span class="navbar-toggler-icon"></span>
        <span class="toggler__txt">メニュー</span>
      </button>
      <div class="navbar-collapse collapse pb-md-0" id="navbarContent">
        <ul class="w-100 navbar-nav pb-3 pb-lg-0 d-flex align-items-center mt-2">
            <li class="nav-item "><%= link_to "使い方", explanation_path , class: "nav-link p-4"%></li>
            <li class="nav-item "><%= link_to "マップページ", maps_path , class: "nav-link p-4"%></li>
            <% if user_signed_in? %>
              <li class="nav-item "><%= link_to "みんなのログブック", "#", class: "nav-link p-4" %></li>
              <li class="nav-item "><%= link_to "ログブック作成", new_user_log_book_path(current_user.id) , class: "nav-link p-4" %></li>
              <li class="nav-item ml-lg-auto"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "nav-link p-4" %>
              <li class="nav-item "><%= link_to current_user.nickname,  users_path(current_user), class: "nav-link p-4" %>
            <% else %>
              <li class="nav-item ml-lg-auto"><%= link_to 'ログイン', new_user_session_path, class: "nav-link p-4" %></li>
              <li class="nav-item "><%= link_to '新規登録', new_user_registration_path, class: "nav-link p-4" %></li>
            <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/static_pages/top.html.erb
<body class="toppage">
<div class="row">
    <div class="col-6">
    <%= image_tag asset_path("kuma.jpeg"),class: "top-image" %>
    </div>
    <div class="col-6 top-right text-center">
      <h1>le grand bleu</h1>
        <p>le grang bleu(当サイト)ではダイビングの海の情報を気軽に投稿、検索すること、及びログブックの管理を簡単にします。</p>
        <ol>
          <li>ログブックをweb上で管理したい</li>
          <li>海の情報を簡単に検索できるようにしたい</li>
          <li>様々なダイバーの写真を一つのサイトで閲覧できるようにしたい</li>
          <li>今まで出会ったダイバーといつまでも繋がっていたい</li>
        </ol>
      <p>上記のような理由を解消したく当サイトを作成しました。まだまだ至らないところや未実装の機能がありますが少しづつ改善していけたらと思っています。</p>  

        <%= link_to "enter", maps_path , class: "btn btn-secondary btn-lg" %>
    </div>
</div>
</body>

app/views/users/index.html.erb
<div class="container emp-profile">
  <div class="row">
      <div class="col-md-4">
          <div class="profile-img">
              <div class="my-image">
                <% if @user.avatar.attached? %>
                  <%= image_tag @user.avatar.variant(resize: '280x280') %>
                <% else %>
                  <%= image_tag asset_path("image1.jpeg"), size: '280x280',class: "dolfin" %>
                <% end %>
              </div>
              <div class="file btn btn-lg btn-primary">
                  画像を変更する
                  <%= form_with model: @user,url: user_path(@user),method: :PUT, class: 'form-edit', local: true do |f| %>
                  <%= f.file_field :avatar %>
              </div>
          </div>
                  <%= f.submit '画像を決定する', class: 'btn btn-primary ml-5' %>
                  <% end %>
      </div>
      <div class="col-md-6">
          <div class="profile-head">
                      <h5><%= @user.nickname %></h5>
                      <h6><%= @user.self_introduction %></h6>
          </div>
      </div>
      <div class="col-md-2">
        <%= link_to "マイページ編集",  edit_user_path(current_user.id), class: "btn btn-outline-primary" %>
      </div>
  </div>
      <div class=" center col-xs-12 divider text-center row justify-content-center">
        <div class="col-xs-12 col-sm-4 emphasis">
          <h2><strong> 20,7K </strong></h2>                    
          <p><small>Following</small></p>
          <button class="btn btn-success btn-block"><span class="fa fa-plus-circle"></span> Follower </button>
      </div>
      <div class="col-xs-12 col-sm-4 emphasis">
        <h2><strong>245</strong></h2>                    
        <p><small>Followed</small></p>
        <button class="btn btn-info btn-block"><span class="fa fa-user"></span> Followed </button>
      </div>
</div>
<h3 class="center mt-5">ログブック一覧</h3>
   <%# <%= will_paginate @log_books  %>
  <div class="log-list">
    <% @log_books.each do |book| %>
      <li class='list'>
        <%= l book.created_at, format: :short %>
        <%= link_to book.place, "/users/#{current_user.id}/log_books/#{book.id}" %>
      </li>
    <% end %>
  </div>
    <%# <%= will_paginate @log_books %>